site_name: Blog
theme:
  name: material
  palette:
    - scheme: slate
      primary: deep purple
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: default
      primary: deep purple
      toggle:
        icon: material/brightness-4 
        name: Switch to light mode
plugins:
  - blog:
      blog_dir: .
